<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Driver.NET.Example</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Driver.NET.DeviceIoControl\Driver.NET.DeviceIoControl.csproj" />
    <ProjectReference Include="..\Driver.NET\Driver.NET.csproj" />
  </ItemGroup>

</Project>
